### ISSUE TITLE
create prod and preprod instances for mis

### ISSUE THREAD

**Issue by enyambudzi** [ministryofjustice/hmpps-mis-terraform-repo#105]

**Comment by jsbarbergit** [comment]
instance sizes updated in https://github.com/ministryofjustice/hmpps-mis-terraform-repo/pull/106
server naming standard needs changing so the legacy_environment_name which currently defaults to ndl-xxx-100 in all environments and for all servers instead uses the following convention requested by mis team:
100 = DEV/Test environment
500 = Preprod
000 = Prod

Also DAM-275 feature branch parameterised the root volume size. For the changes to be applied the userdata script needs an additional powershell step to extend the volume from the AMI value if needed.

**Comment by jsbarbergit** [comment]
MIS Team have asked for Prod to include a 3rd instance of BCS too
